version: 0.2

phases:
  install:
    commands:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - sudo apt update -y 
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/my-app-1.0-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes
