version: 0.2

phases:
  install:
    commands:
    runtime-versions:
      java: corretto8 
  pre_build:
    commands:
      - apt-get update
      - apt install -y openjdk-8-jdk openjdk-8-jre
      - apt-get install -y maven
  build:
    commands: 
      - mav -v
      - echo Build started on `date`
      - mvn package 
#  post_build:
#    commands:
#      - echo Build completed on `date`
#      - mvn package
artifacts:
  files:
    - target/my-app-1.0-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes
